project_id = "uqisnapayiofyiwpknag"

[functions.import-data]
verify_jwt = false

[functions.import-staff]
verify_jwt = false

[functions.reset-staff-password]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false

[functions.export-database]
verify_jwt = false

[functions.migrate-openpos]
verify_jwt = false

[functions.sync-menu-inventory]
verify_jwt = false
